checkpoint:
  path: "mfcc_specrnet/weights.pth"
data:
  seed: 42
model:
  name: specrnet
  optimizer:
    lr: 0.0001
    weight_decay: 0.0001
  parameters:
    frontend_algorithm:
    - mfcc
    input_channels: 1
