checkpoint:
  path: "whisper_lcnn_finetuned/weights.pth"
data:
  seed: 42
model:
  name: whisper_lcnn
  optimizer:
    lr: 1.0e-06
    weight_decay: 0.0001
  parameters:
    freeze_encoder: false
    frontend_algorithm:
    - lfcc
    input_channels: 1
