checkpoint:
  path: "whisper_mfcc_specrnet/weights.pth"
data:
  seed: 42
model:
  name: whisper_frontend_specrnet
  optimizer:
    lr: 0.0001
    weight_decay: 0.0001
  parameters:
    freeze_encoder: true
    frontend_algorithm:
    - mfcc
    input_channels: 2
