checkpoint:
  path: "whisper_mesonet_finetuned/weights.pth"
data:
  seed: 42
model:
  name: whisper_mesonet
  optimizer:
    lr: 1.0e-06
    weight_decay: 0.0001
  parameters:
    fc1_dim: 1024
    freeze_encoder: false
    frontend_algorithm: []
    input_channels: 1
